import { app, BrowserWindow, ipcMain, net, protocol } from 'electron';
import path from 'path';
import { pathToFileURL } from 'node:url';
import { getDb } from './main/db';
import { registerDbHandlers } from './main/dbHandlers';
import { getMediaDir } from './main/mediaStorage';
import { importZip, importZips, inspectZip } from './main/importZip';
import type { ImportProgress } from './types/import';
// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
// eslint-disable-next-line @typescript-eslint/no-require-imports -- electron-squirrel-startup must be required synchronously
if (require('electron-squirrel-startup')) {
  app.quit();
}

protocol.registerSchemesAsPrivileged([
  {
    scheme: 'chatwrapped-media',
    privileges: { standard: true, supportFetchAPI: true, stream: true },
  },
]);

let mainWindow: BrowserWindow | null = null;

const createWindow = (): void => {
  // Create the browser window.
  mainWindow = new BrowserWindow({
    height: 600,
    width: 800,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
      contextIsolation: true,
      nodeIntegration: false,
      sandbox: true,
    },
  });

  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  // Open DevTools only in development
  if (process.env.NODE_ENV === 'development' || !app.isPackaged) {
    mainWindow.webContents.openDevTools();
  }

  mainWindow.on('closed', () => {
    mainWindow = null;
  });
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', () => {
  protocol.handle('chatwrapped-media', (request) => {
    const url = new URL(request.url);
    const pathname = decodeURIComponent(url.pathname.slice(1));
    if (!pathname || pathname.includes('..')) {
      return new Response('Not Found', { status: 404 });
    }
    const mediaDir = getMediaDir();
    const resolvedPath = path.resolve(mediaDir, pathname);
    const relative = path.relative(mediaDir, resolvedPath);
    if (relative.startsWith('..') || path.isAbsolute(relative)) {
      return new Response('Forbidden', { status: 403 });
    }
    return net.fetch(pathToFileURL(resolvedPath).toString());
  });
  registerDbHandlers(getDb);
  createWindow();
});

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

ipcMain.handle('import:inspect', async (_, zipPath: string) => {
  return inspectZip(zipPath);
});

ipcMain.handle('import:start', async (_, zipPath: string) => {
  const db = getDb();
  const onProgress = (p: ImportProgress) => {
    if (mainWindow && !mainWindow.isDestroyed()) {
      mainWindow.webContents.send('import:progress', p);
    }
  };
  return importZip(zipPath, db, onProgress);
});

ipcMain.handle('import:start-multi', async (_, zipPaths: string[]) => {
  const db = getDb();
  const onProgress = (p: ImportProgress) => {
    if (mainWindow && !mainWindow.isDestroyed()) {
      mainWindow.webContents.send('import:progress', p);
    }
  };
  return importZips(zipPaths, db, onProgress);
});
